### PR TITLE
single card form page and profile redesign.

### PR DESCRIPTION
**Pull request by Sultan7rs**
I made changes that are up to date with the master. There are additional modules I installed:

- workerize-loader
- js-cookie 
- mapbox-gl
- vue-mapbox
- @capacitor/geolocation

Let me know if there are issues.

### CODE REVIEW

**Comment by ryandahan2001** [comment]
if you can get me the command that worked for you. Mine is returning errors that ( I think ) are out of my control

**Comment by ryandahan2001** [comment]
`Uncaught (in promise) TypeError: input buffer is not a HEIC image `
causes a error lock

**Comment by ryandahan2001** [comment]
it looks good otherwise

**Comment by Sultan7rs** [comment]
> `Uncaught (in promise) TypeError: input buffer is not a HEIC image `
> causes a error lock

Can I get the image file you used that cause  that error?

**Pull request closed without merging**
